### ISSUE TITLE
Assembly conflict between LaunchDarkly.Client and Microsoft.Extensions.Logging.Abstractions packages

### ISSUE THREAD

**Issue by arrowsmithm** [launchdarkly/hello-dotnet#6]
Hi,

I've cloned this console app locally and restored NuGet packages on my developer machine, however when running the application I get a conflict between the between LaunchDarkly.Client and Microsoft.Extensions.Logging.Abstractions packages:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'LaunchDarkly.Client' with identity 'LaunchDarkly.Client, Version=3.6.1.0, Culture=neutral, PublicKeyToken=f86add69004e6885' uses 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with identity 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	HelloDotNet	C:\repos\hello-dotnet\HelloDotNet\Program.cs	15	Active

Regards,
Mark

**Comment by eli-darkly** [comment]
Hi. In the 4.0.0 release of the client, we've switched from Microsoft.Extensions.Logging to Common.Logging. The hello-dotnet app has now been updated for this; could you try pulling the latest version and let us know the result?

**Comment by bwoskow-ld** [comment]
I'm closing this issue as over a year has passed since the most recent response and we believe the issue has been resolved. Feel free to reach out to us again if you continue to run into any issues.
